version: '3.8'

services:
  # Cluster Node 1: Primary Telemetry Ingestion Node
  Clinical-ingestion-core:
    build:
    container_name: enterprise_clinical_cluster_node_1
    restart: always
    volumes:
      - .:/app
      - DEPLOYMENT_TIER=Princial-Architect-V